/**
 * Job Description (JD) Plugin Configuration
 */

export const jdPlugin = {
  id: 'jd',
  name: 'Job Description',
  icon: '💼',
  description: 'Create inclusive, compelling job descriptions',
  dbName: 'jd-docforge-db',

  formFields: [
    {
      id: 'jobTitle',
      label: 'Job Title',
      type: 'text',
      required: true,
      placeholder: 'e.g., Senior Software Engineer',
    },
    {
      id: 'companyName',
      label: 'Company Name',
      type: 'text',
      required: true,
      placeholder: 'e.g., Acme Corp',
    },
    {
      id: 'roleLevel',
      label: 'Role Level',
      type: 'select',
      required: false,
      options: [
        { value: 'entry', label: 'Entry Level' },
        { value: 'mid', label: 'Mid Level' },
        { value: 'senior', label: 'Senior' },
        { value: 'staff', label: 'Staff' },
        { value: 'principal', label: 'Principal' },
        { value: 'manager', label: 'Manager' },
        { value: 'director', label: 'Director' },
      ],
    },
    {
      id: 'location',
      label: 'Location / Remote',
      type: 'text',
      required: false,
      placeholder: 'e.g., San Francisco, CA (Hybrid) or Remote',
    },
    {
      id: 'postingType',
      label: 'Posting Type',
      type: 'select',
      required: true,
      options: [
        { value: 'external', label: 'External Posting' },
        { value: 'internal', label: 'Internal Posting' },
        { value: 'both', label: 'Both Internal & External' },
      ],
    },
    {
      id: 'responsibilities',
      label: 'Key Responsibilities',
      type: 'textarea',
      required: false,
      rows: 3,
      placeholder: 'What will this person do day-to-day?',
    },
    {
      id: 'requiredQualifications',
      label: 'Required Qualifications',
      type: 'textarea',
      required: false,
      rows: 3,
      placeholder: 'Must-have skills, experience, qualifications...',
    },
    {
      id: 'preferredQualifications',
      label: 'Preferred Qualifications',
      type: 'textarea',
      required: false,
      rows: 2,
      placeholder: 'Nice-to-have but not required skills...',
    },
    {
      id: 'compensationRange',
      label: 'Compensation Range',
      type: 'text',
      required: false,
      placeholder: 'e.g., $150K-$200K + equity',
    },
    {
      id: 'benefits',
      label: 'Benefits',
      type: 'textarea',
      required: false,
      rows: 2,
      placeholder: 'Health, 401k, PTO, etc...',
    },
    {
      id: 'techStack',
      label: 'Tech Stack',
      type: 'textarea',
      required: false,
      rows: 2,
      placeholder: 'e.g., Python, TypeScript, AWS, Kubernetes...',
    },
    {
      id: 'teamSize',
      label: 'Team Size / Structure',
      type: 'text',
      required: false,
      placeholder: 'e.g., 8-person team, 2 pods',
    },
    {
      id: 'aiSpecifics',
      label: 'AI Role Specifics',
      type: 'textarea',
      required: false,
      rows: 2,
      placeholder: 'For AI roles: models used, infrastructure, research focus...',
    },
    {
      id: 'careerLadder',
      label: 'Career Ladder Reference',
      type: 'textarea',
      required: false,
      rows: 2,
      placeholder: 'Growth path, leveling expectations...',
    },
    {
      id: 'companyPreamble',
      label: 'Company Preamble / EEO',
      type: 'textarea',
      required: false,
      rows: 2,
      placeholder: 'Standard company intro and equal opportunity statement...',
    },
    {
      id: 'companyLegalText',
      label: 'Legal Text',
      type: 'textarea',
      required: false,
      rows: 2,
      placeholder: 'Any required legal disclosures...',
    },
  ],

  scoringDimensions: [
    { name: 'Clarity', maxPoints: 25, description: 'Clear role, responsibilities, requirements' },
    {
      name: 'Inclusivity',
      maxPoints: 25,
      description: 'Gender-neutral language, reasonable requirements',
    },
    {
      name: 'Completeness',
      maxPoints: 25,
      description: 'All sections present, team context, growth opportunity',
    },
    { name: 'Appeal', maxPoints: 25, description: 'Compelling, authentic, differentiating' },
  ],

  validateDocument: null,

  workflowConfig: {
    phaseCount: 3,
    phases: [
      {
        number: 1,
        name: 'Draft JD',
        icon: '📝',
        aiModel: 'Claude',
        description: 'Generate job description draft',
      },
      {
        number: 2,
        name: 'Inclusivity Review',
        icon: '🔍',
        aiModel: 'Gemini',
        description: 'Check inclusivity with Gemini',
      },
      {
        number: 3,
        name: 'Final JD',
        icon: '✨',
        aiModel: 'Claude',
        description: 'Combine into polished JD',
      },
    ],
  },
};
