# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "e2e/**/*"
  - "scripts/**/*"
  - "docs/**/*"
  - "node_modules/**/*"
  - "*.config.js"
  - "*.setup.js"
  - "shared/js/lib/**/*"

